services:
  pdf_processor:
    build: .
    container_name: pdf_processor
    volumes:
      - ./input:/usr/src/app/input  
      - ./output:/usr/src/app/output 
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/
    mem_limit: 4g
    memswap_limit: 4g
    command: ["python", "classify.py", "input/test_first_100_pages.pdf", "output"]